version: "3.3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "news"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "hoanqnqu"
      # You can use whatever password you like
      MYSQL_PASSWORD: "0000"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "0000"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
